### PR TITLE
Time period

### LINKED ISSUE #124: 12 hour setting on clock but not on forecasts
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Clock on top shows AM/PM with IS_STYLE_12HR setting set to true. Currently the clock shows 6:15pm. Under clock is current conditions. Under current conditions is the forecast scrolling right to left. Under the forecast is the moon information with rise and set times. 

### Actual behavior
The times for the forecast currently show 8:00 and 20:00 rather than 8am and 8pm. Moon rise and set times show 06:00 and 19:00 rather than 6:00am and 7:00pm.

### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.

```c
// pick one from https://github.com/esp8266/Arduino/blob/master/cores/esp8266/TZ.h
#define TIMEZONE TZ_America_New_York

// values in metric or imperial system?
const boolean IS_METRIC = false;

// Change for 12 Hour/ 24 hour style clock
bool IS_STYLE_12HR = true;
```
### Weather Station Color version
Master code branch. 

### Hardware
2.8" TFT touch display with ESP8266 D1 pro
WeMos D1 Mini ESP8266 WIFI Module Board Pro 16M
240x320 2.8" SPI TFT LCD Touch Panel Serial Port Module With PBC ILI9341 2.8 Inch SPI Serial White LED Display

8<------------------------ END BUG REPORT -------------------------------------

### PR DESCRIPTION
**Pull request by TiVoHomeUser**
Fixes #124 & #127.

- [x] This PR is compliant with the [other contributing guidelines](https://github.com/ThingPulse/esp8266-weather-station-color/blob/master/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] Should this code require changes to documentation I will contribute those to [https://github.com/ThingPulse/docs](https://github.com/ThingPulse/docs).

 - Fix for broken sleep mode
 - Soft sleep mode
 - Fix for 12/24 hr displays not changing

### CODE REVIEW

**Review by SillyHats — CHANGES_REQUESTED** [review]
Thanks for fixing this. For 12h formatting preferences I changed %02d to %2d to remove leading zeros in the times on my board.

**Comment by TiVoHomeUser** [comment]
Nice 8:00 PM is better then 08:00 PM for the 12 HR format

**Review by TiVoHomeUser — COMMENTED** [review]
Fix for Sleep mode and added Light off sleep mode with screen press wake
Change for 12/24 hr format in forcast

**Comment by TiVoHomeUser** [comment]
Ready

**Comment by TiVoHomeUser** [comment]
Fixed conflicts any thing more I need to do?

**Comment by marcelstoer** [comment]
😢 😞 so sorry I missed to review this in due time. Hope I'll find some time next week.

**Pull request merged**
