### PR TITLE
Added ESP32 support

### PR DESCRIPTION
**Pull request by anabolyc**
Fixes #\<GitHub-issue-number\>.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [ ] This PR is compliant with the [other contributing guidelines](https://github.com/ThingPulse/esp8266-weather-station-color/blob/master/CONTRIBUTING.md) as well (if not, please describe why).
- [ ] I have thoroughly tested my contribution.
- [ ] Should this code require changes to documentation I will contribute those to [https://github.com/ThingPulse/docs](https://github.com/ThingPulse/docs).

\<Description of and rationale behind this PR\>

### CODE REVIEW

**Comment by edasque** [comment]
So this was never merged, was it?

**Comment by anabolyc** [comment]
I've created it accidentally, intention was to keep in in fork. My changes would break upstream repo.

**Comment by edasque** [comment]
Gotcha. I can't create issues on https://github.com/anabolyc/esp32-esp8266-weather-station-color - do you think it would work on a LILYGO TTGO T-Display ESP32 (IPS ST7789V 1.14 Inch at 135px*240px) and if not, what should I be looking at to make it work (guessing you don't support that display resolution), @anabolyc ?

**Comment by anabolyc** [comment]
@edasque I'm using same display controller and don't have touch, so it will work. Please have a look at platformio.ini file and make pinout and screen size adjustments, it should work with no code changes apart from that.

**Comment by edasque** [comment]
Some of that worked but not the display. Serial monitor gets up to:
```
start document
Free mem: 264904
```

with
```
	-D ST7789_TFTWIDTH=135
	-D ST7789_TFTHEIGHT=240
	-D TFT_CS=5
	-D TFT_RST=23
	-D TFT_DC=16
	-D TFT_LED=4
	-D TFT_ROTATION=0
	-D TFT_MOSI=19
	-D TFT_SCLK=18
```

Where would you start debugging?

**Comment by anabolyc** [comment]
@edasque pinout seems right, MOSI and SCLK is redundant, since it is configured as HW SPI. Really hard to say without having board to poke around. 
I'd try to run Bodmer's `TFT_eSPI` and `Adafruit ST7789` lib samples, as soon as you'd get it to work you can check what is the initialization code that works.

**Pull request closed without merging**
